config/routes.rb
Rails.application.routes.draw do
  get    'tasks', to: 'tasks#index'

  get    'tasks/new', to: 'tasks#new'
  post   'tasks', to: 'tasks#create'

  # NB: The `show` route needs to be *after* `new` route.
  get    'tasks/:id', to: 'tasks#show', as: 'task'

  get    'tasks/:id/edit', to: 'tasks#edit', as: 'edit_task'
  patch  'tasks/:id', to: 'tasks#update'

  delete 'tasks/:id', to: 'tasks#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]

  def index
    @tasks = Task.all
  end

  def show
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    # pick up info on the params and create a new task with the info
    @task.save
    # save it
    redirect_to tasks_path
    # redirect to another page
  end

  def edit
  end

  def update
    @task.update(task_params)
    # pick up info on the params and update the task
    redirect_to @task
    # redirect to another page
  end

  def destroy
    @task.destroy
    # delete the task
    redirect_to tasks_path
    # redirect to another page
  end

  private

  def set_task
    @task = Task.find(params[:id])
  end

  def task_params
    params.require(:task).permit(:title, :details, :completed)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <title>My Tasks</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= form_for(@task) do |f| %>
  <div class="form-control">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>
  <div class="form-control">
    <%= f.label :details %>
    <%= f.text_field :details %>
  </div>
  <div class="form-control">
    <%= f.label "Completed" %> <br />
    <%= f.check_box :completed, {}, true, false %> <br />
  </div>

  <%= f.submit class: "btn btn-primary" %>
<% end %>

app/views/tasks/edit.html.erb
<%= render "form" %>

app/views/tasks/index.html.erb
<div class="container ml-3 p-2">
<h1>All My Tasks</h1>
<br>

<% @tasks.each do |task| %>
<ul class="list-group">
  <li class="list-group-item">
  <input class="form-check-input" type="checkbox" id="defaultCheck1" name="completed" <%= "checked" if task[:completed] %>>
  <%= link_to task.title, task_path(task) %>
</li>
<% end %>
</ul>
<br>
<br>
<%= link_to "Add new task", tasks_new_path %>
</div>

app/views/tasks/new.html.erb
<%= render "form" %>

app/views/tasks/show.html.erb
<h2><%= @task.title %></h2>
<p><%= @task.details %></p>
<input type="checkbox" name="completed" <%= "checked" if @task[:completed] %>>

<br>
<br>

<%= link_to "Edit task |", edit_task_path(@task) %>

<%= link_to " Delete task", task_path(@task),
      method: :delete,
      data: { confirm: "Are you sure?" } %>